### ISSUE TITLE
Setting crashes when opening Network & Internet -> SIM Cards

### ISSUE THREAD

**Issue by growtopiajaw** [DirtyUnicorns/android_packages_apps_Settings#10]
Logcat:
11-22 19:41:40.430 I/ActivityManager(1022): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.android.settings/.Settings bnds=[360,946][475,1113]} from uid 1000
11-22 19:41:40.469 I/ActivityManager(1022): Start proc 6066:com.android.settings/1000 for activity com.android.settings/.Settings
11-22 19:41:40.648 W/TileUtils(6066): Ignoring icon tintable for ActivityInfo{ffbd405 com.google.android.gms.security.settings.VerifyAppsSettingsActivity}
11-22 19:41:40.649 W/TileUtils(6066): Ignoring icon tintable for ActivityInfo{9b0fc5a com.google.android.gms.security.settings.AdmSettingsActivity}
11-22 19:41:40.708 D/SuggestionParser(6066): Day 0 for com.android.settings.suggested.category.FIRST_IMPRESSION
11-22 19:41:40.775 I/com.android.settings(6066): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
11-22 19:41:40.855 D/Settings(6066): No enabled state changed, skipping updateCategory call
11-22 19:41:40.870 I/ActivityManager(1022): Displayed com.android.settings/.Settings: +414ms (total +36s783ms)
11-22 19:41:44.293 I/ActivityManager(1022): START u0 {flg=0x8000 cmp=com.android.settings/.Settings$NetworkDashboardActivity (has extras)} from uid 1000
11-22 19:41:44.531 I/zygote64(6066): Deoptimizing java.util.List com.android.settingslib.drawer.TileUtils.getCategories(android.content.Context, java.util.Map, boolean, java.lang.String, java.lang.String) due to JIT inline cache
11-22 19:41:44.580 D/Settings(6066): No enabled state changed, skipping updateCategory call
11-22 19:41:44.781 I/ActivityManager(1022): Displayed com.android.settings/.Settings$NetworkDashboardActivity: +466ms
11-22 19:41:46.063 I/ActivityManager(1022): START u0 {act=android.intent.action.MAIN cmp=com.android.settings/.SubSettings (has extras)} from uid 1000
11-22 19:41:46.151 D/SubSettings(6066): Launching fragment com.android.settings.sim.SimSettings
11-22 19:41:46.157 E/AndroidRuntime(6066): Process: com.android.settings, PID: 6066
11-22 19:41:46.157 E/AndroidRuntime(6066): 	at com.android.settings.sim.SimSettings.onCreate(SimSettings.java:136)
11-22 19:41:46.157 E/AndroidRuntime(6066): 	at com.android.settings.SettingsActivity.switchToFragment(SettingsActivity.java:758)
11-22 19:41:46.157 E/AndroidRuntime(6066): 	at com.android.settings.SettingsActivity.launchSettingFragment(SettingsActivity.java:435)
11-22 19:41:46.157 E/AndroidRuntime(6066): 	at com.android.settings.SettingsActivity.onCreate(SettingsActivity.java:327)
11-22 19:41:46.157 E/AndroidRuntime(6066): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.codeaurora.internal.IExtTelephony$Stub" on path: DexPathList[[zip file "/system/priv-app/Settings/Settings.apk"],nativeLibraryDirectories=[/system/priv-app/Settings/lib/arm64, /system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]
11-22 19:41:46.161 W/ActivityManager(1022):   Force finishing activity com.android.settings/.SubSettings
11-22 19:41:46.164 W/ActivityManager(1022):   Force finishing activity com.android.settings/.Settings$NetworkDashboardActivity
11-22 19:41:46.170 I/ActivityManager(1022): Showing crash dialog for package com.android.settings u0
11-22 19:41:46.662 W/ActivityManager(1022): Activity pause timeout for ActivityRecord{c77e38e u0 com.android.settings/.SubSettings t26 f}
11-22 19:41:48.703 W/ActivityManager(1022):   Force finishing activity com.android.settings/.SubSettings
11-22 19:41:48.705 W/ActivityManager(1022):   Force finishing activity com.android.settings/.Settings$NetworkDashboardActivity
11-22 19:41:48.711 W/ActivityManager(1022):   Force finishing activity com.android.settings/.Settings
11-22 19:41:48.763 E/ActivityManager(1022): Found activity ActivityRecord{a9154a0 u0 com.android.settings/.Settings t-1 f} in proc activity list using null instead of expected ProcessRecord{9b37b5c 6066:com.android.settings/1000}
11-22 19:41:48.774 I/ActivityManager(1022): Killing 6066:com.android.settings/1000 (adj 199): crash
11-22 19:41:48.846 W/InputDispatcher(1022): channel '3206df5 com.android.settings/com.android.settings.Settings (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
11-22 19:41:48.846 E/InputDispatcher(1022): channel '3206df5 com.android.settings/com.android.settings.Settings (server)' ~ Channel is unrecoverably broken and will be disposed!
11-22 19:41:48.853 I/WindowManager(1022): WIN DEATH: Window{44e13b6 u0 com.android.settings/com.android.settings.Settings$NetworkDashboardActivity}
11-22 19:41:48.855 I/WindowManager(1022): WIN DEATH: Window{3206df5 u0 com.android.settings/com.android.settings.Settings}
11-22 19:41:48.855 W/InputDispatcher(1022): Attempted to unregister already unregistered input channel '3206df5 com.android.settings/com.android.settings.Settings (server)'

**Comment by nychitman1** [comment]
We're not currently accepting "bug" reports.
