### ISSUE TITLE
Please add slovak language (values-sk) to Crowdin

### ISSUE THREAD

**Issue by rbarat** [DirtyUnicorns/android_packages_apps_Settings#6]
HI, please add slovak language (sk) to DirtyUnicorns on Crowdin and give me proofreader rights also. I am experienced translator, member of many projects there. Will make slovak translates for this project.

Thank you much. 

https://crowdin.com/project/dirtyunicorns

Robert

**Comment by nychitman1** [comment]
We'll discuss it.
