### ISSUE TITLE
Can I prepare a Slovak translation (values-sk) and upload it here?

### ISSUE THREAD

**Issue by rbarat** [DirtyUnicorns/android_packages_apps_Settings#8]
Can I prepare a Slovak translation (values-sk) and upload it here? Will you add it to the project? I ask in advance not to do it unnecessarily. I use this ROM on Redmi Note 3 and I miss the Slovak translation of DirtyTweaks. Thanks you in advance.

**Comment by BoredOutOfMyGit** [comment]
No we don't accept pull requests. Submit things via gerrit if you wish.

https://gerrit.dirtyunicorns.com/

**Comment by rbarat** [comment]
I can not work with Gerrit. Perhaps it would be better to add values-sk to Crowdin translations. It can not be? Please.

**Comment by BoredOutOfMyGit** [comment]
I've told you a number of times (on here, Twitter, G+, etc) that it will be created but you have to have patience. You keep spamming us and really is making me not want to do it at all.

In case there's a language barrier, having patience means to wait. It doesn't mean annoy the other party until they do what you ask.

Again, it will get added to crowdin. You just have to wait. Stop spamming us. Please.
