### ISSUE TITLE
To Alex Cruz (Mazda)

### ISSUE THREAD

**Issue by rbarat** [DirtyUnicorns/android_packages_apps_Settings#9]
Alex,

I'm sorry if you perceive it as spam.
I was just that DIrtyUnicorns is really a good project and I wanted to help with the translation.
I'm the author of Slovak translations for many different ROMs.
I wanted and still want to make a slovak translation for Dirty Unicorns - I am using this ROM myself.

Well, I'll wait until you add the Slovak language to Crowdin.net.
I just hope it does not take long. Many people from our forum https://androidforum.cz would like to have Slovak.

Once again, I apologize if I caused you any problems.

Robert

**Comment by nychitman1** [comment]
It will take however long it takes. Stop spamming us with GitHub issues.
